feat: Raster App
contentful/marketplace-partner-apps pull request #2284
Opened 2024-07-12 20:40 UTC by emwp

## Purpose
Raster enables users to leverage their existing media assets and easily use them in their Contentful projects.

## Approach
Field View:
![image](https://github.com/user-attachments/assets/8aa6dbaf-7846-4a10-872c-baf23c12b473)

Dialog View:
![image](https://github.com/user-attachments/assets/e918c46a-dc70-4af4-b344-eb81b1d451a0)

## Testing steps
1. Install the app.
2. Include JSON Object field on content model.
3. Change the above field appearance to use Raster.
4. Create an entry and test the Raster field – You can select a single image or multiple images from different libraries.

## Breaking Changes
No breaking changes.

2024-07-14 15:13 UTC, lambardi commented
Thanks! We'll get a CR started ASAP.

2024-07-15 16:01 UTC, emwp commented
> Thanks! We'll get a CR started ASAP.

Hey @lambardi, thanks!
One thing I wanted to make, our app is a Next.js app, I believe apps need to be hosted by Contentful, right?
Can Contentful host the Next.js app? I ask because I noticed all other apps are using CRA/Vite.

2024-07-19 18:10 UTC, whitelisab requested changes
We added some comments for you to review and address. In addition to those comments, here are few other things to consider:

- Please add a license file for your app. You can review other apps in this repo as a reference (e.g.: https://github.com/contentful/marketplace-partner-apps/blob/main/apps/wix/LICENSE). 
- Confirm that your app adheres to OWASP standards: https://owasp.org/www-project-top-ten/
- Confirm that your app meets basic accessibility standards: https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML

2024-07-27 23:56 UTC, emwp commented on apps/raster/package.json
> +  "version": "1.0.0",
Done!

2024-07-27 23:57 UTC, emwp commented on apps/raster/package.json
> +  "scripts": {
Sure! I've added some testing for the ConfigScreen, Field and Dialog components.

2024-07-27 23:57 UTC, emwp commented on apps/raster/package.json
> +    "deploy": "contentful-app-scripts upload --ci --bundle-dir ./dist --organization-id ${DEFINITIONS_ORG_ID} --definition-id 41ISJmeSvLGsYT60RfIqyd --token ${CONTENTFUL_CMA_TOKEN}"
Done!

2024-07-27 23:59 UTC, emwp commented on apps/raster/src/components/locations/ConfigScreen.tsx
> +    apiKey: "",
The `apiKey` from Raster is for read only, not necessarily a secret.

2024-07-29 00:23 UTC, emwp commented
@whitelisab Seem to be having some issue with node/npm version.
That's why I had removed the eslint config before haha, but I've tried with many node versions that should be on the accepted range and still getting this issue. Also see that other apps have the same dependency installed with no issues.

https://app.circleci.com/pipelines/github/contentful/marketplace-partner-apps/8553/workflows/13d9b627-d21f-44cf-a3f3-91f62c61c86f/jobs/7053

2024-08-14 21:50 UTC, t-col commented
hi @emwp, I'm taking over for @whitelisab here. Regarding the CI issue with node versions: if you rebase you should see that go away. I believe the problem was with the node version that we had pinned in the root `.npmrc`, which I fixed [here](https://github.com/contentful/marketplace-partner-apps/pull/2521).

2024-08-19 20:10 UTC, t-col requested changes
@emwp looks like we're just missing a LICENSE file. Once we have that I can get this merged. See [this one](https://github.com/contentful/marketplace-partner-apps/blob/main/apps/wix/LICENSE) as a reference

2024-08-19 20:22 UTC, emwp commented
> @emwp looks like we're just missing a LICENSE file. Once we have that I can get this merged. See [this one](https://github.com/contentful/marketplace-partner-apps/blob/main/apps/wix/LICENSE) as a reference

Thanks @t-col, License is added.

2024-08-19 20:23 UTC, t-col approved these changes

2024-08-19 20:28 UTC, merged

2024-08-22 19:39 UTC, t-col commented
hi @emwp - can you confirm that you were able to upload your app (Contentful hosted, as opposed to served locally) to a test org and install it to a space/env successfully? I'm unable to do so for the production deployment.

2024-08-27 14:15 UTC, emwp commented
> hi @emwp - can you confirm that you were able to upload your app (Contentful hosted, as opposed to served locally) to a test org and install it to a space/env successfully? I'm unable to do so for the production deployment - the app does not render at all, and there appears to be an issue fetching the built assets from the HTML file (maybe a CORS issue). I unsuccessfully attempted to tweak the next.js build config to resolve the issues I'm seeing, but no luck. Please let me know if you experience this issue when you build and upload the app on your end.

Hey @t-col – I can't confirm if I did exactly that, what I did was with the build folder (where it says to drag it to on Contentful).
I believe the best solution is to just migrate this to a CRA/Vite app, we started as a Next.js app just by default without knowing how the deployment process would be for Contentful.

I've already migrated most of it to Vite app, will ping you here when I open a PR for this.

2024-08-27 14:50 UTC, t-col commented
hey @emwp we use a utility from `contentful-app-scripts` that looks exactly like this: https://github.com/contentful/create-contentful-app/blob/main/packages/contentful--app-scripts/README.md#non-interactive-mode
Use this as a reference in uploading to your own space.

2024-08-27 14:54 UTC, emwp commented
> hi @emwp - can you confirm that you were able to upload your app (Contentful hosted, as opposed to served locally) to a test org and install it to a space/env successfully? I'm unable to do so for the production deployment - the app does not render at all, and there appears to be an issue fetching the built assets from the HTML file (maybe a CORS issue). I unsuccessfully attempted to tweak the next.js build config to resolve the issues I'm seeing, but no luck. Please let me know if you experience this issue when you build and upload the app on your end.

Just added the PR here if you can take a look:
https://github.com/contentful/marketplace-partner-apps/pull/2699